import * as Yup from "yup";

export const initialRegisterPurchaseValues = {
  empresa: "",
  filial: "",
  placa: "",
  marca: "",
  modelo: "",
  ano: "",
  anoFabricacao: "",
  versao: "",
  cambio: "",
  numeroPortas: "",
  cor: "",
  combustivel: "",
  renavan: "",
  origem: "",
  avaliador: "",
  patio: "",
  tipoRecibo: "",
  tipoVeiculo: "Novo",
  blindado: "Não",
  sucata: "Não",
  leilao: "Não",

  clienteFornecedor: "",
  //Proprietário Pessoa Física
  nome: "",
  dataNascimento: "",
  sexo: "",
  estadoCivil: "",
  possuiFilhos: "Não",
  email: "",
  telefone: "",
  ramoAtividade: "",
  rendaMensal: "",
  classificacao: "Cliente",
  cpf: "",
  rg: "",
  cnh: "",
  vencimentoCnh: "",
  endereco: "",
  numero: "",
  complemento: "",
  bairro: "",
  cidade: "",
  estado: "",
  observacoes: "",

  //Proprietário Pessoa Jurídica
  cnpj: "",
  ie: "",
  ramoAtividadeJuridica: "",
  classificacaoJuridica: "Cliente",
  possuiFilhosJuridica: "Não",
  nomeRepresentante: "",
  emailRepresentante: "",
  telefoneRepresentante: "",
  contaComercial: "",
  cnhRepresentante: "",
  vencimentoCnhRepresentante: "",
  enderecoRepresentante: "",
  numeroRepresentante: "",
  complementoRepresentante: "",
  bairroRepresentante: "",
  cidadeRepresentante: "",
  estadoRepresentante: "",
  observacoesRepresentante: "",

  //Dados intermediario
  clienteFornecedorIntermediario: "",
  nomeIntermediario: "",
  dataNascimentoIntermediario: "",
  sexoIntermediario: "",
  estadoCivilIntermediario: "",
  possuiFilhosIntermediario: "Não",
  emailIntermediario: "",
  telefoneIntermediario: "",
  ramoAtividadeIntermediario: "",
  rendaMensalIntermediario: "",
  classificacaoIntermediario: "Cliente",
  cpfIntermediario: "",
  rgIntermediario: "",
  cnhIntermediario: "",
  vencimentoCnhIntermediario: "",
  enderecoIntermediario: "",
  numeroIntermediario: "",
  complementoIntermediario: "",
  bairroIntermediario: "",
  cidadeIntermediario: "",
  estadoIntermediario: "",
  observacoesIntermediario: "",

  //Dados intermediario pessoa juridica
  cnpjIntermediario: "",
  ieIntermediario: "",
  ramoAtividadeJuridicaIntermediario: "",
  classificacaoJuridicaIntermediario: "Cliente",
  possuiFilhosJuridicaIntermediario: "Não",
  nomeRepresentanteIntermediario: "",
  emailRepresentanteIntermediario: "",
  telefoneRepresentanteIntermediario: "",
  contaComercialIntermediario: "",
  cnhRepresentanteIntermediario: "",
  vencimentoCnhRepresentanteIntermediario: "",
  enderecoRepresentanteIntermediario: "",
  numeroRepresentanteIntermediario: "",
  complementoRepresentanteIntermediario: "",
  bairroRepresentanteIntermediario: "",
  cidadeRepresentanteIntermediario: "",
  estadoRepresentanteIntermediario: "",
  observacoesRepresentanteIntermediario: "",

  formaPagamento: "",
  valorPagamento: 0,
  dataPagamento: "",
  informacoesReferentePagamento: "",
};

export const formSchemaRegisterPurchase = Yup.object().shape({
  empresa: Yup.string().required("Campo obrigatório"),
  filial: Yup.string().required("Campo obrigatório"),
  modelo: Yup.string().required("Campo obrigatório"),
  ano: Yup.string().required("Campo obrigatório"),
  anoFabricacao: Yup.string().required("Campo obrigatório"),
  versao: Yup.string().required("Campo obrigatório"),
  renavan: Yup.string().required("Campo obrigatório"),
  origem: Yup.string().required("Campo obrigatório"),
  avaliador: Yup.string().required("Campo obrigatório"),
  patio: Yup.string().required("Campo obrigatório"),
  tipoRecibo: Yup.string().required("Campo obrigatório"),
  clienteFornecedor: Yup.string().required("Campo obrigatório"),
  clienteFornecedorIntermediario: Yup.string().required("Campo obrigatório"),
});
